server:
  port: 8761  # Default port for Eureka Server

spring:
  application:
    name: eureka-server  # Name of the service

eureka:
  client:
    register-with-eureka: false  # Do not register itself
    fetch-registry: false  # Do not fetch registry from itself
  server:
    wait-time-in-ms-when-sync-empty: 5
